// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: metrics.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsClient interface {
	// SendMetric отправка в потоке атомарной метрики
	SendMetric(ctx context.Context, opts ...grpc.CallOption) (Metrics_SendMetricClient, error)
	// SendMetrics отправка слайса метрик
	SendMetrics(ctx context.Context, in *GRPCMetric, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type metricsClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsClient(cc grpc.ClientConnInterface) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) SendMetric(ctx context.Context, opts ...grpc.CallOption) (Metrics_SendMetricClient, error) {
	stream, err := c.cc.NewStream(ctx, &Metrics_ServiceDesc.Streams[0], "/proto.Metrics/SendMetric", opts...)
	if err != nil {
		return nil, err
	}
	x := &metricsSendMetricClient{stream}
	return x, nil
}

type Metrics_SendMetricClient interface {
	Send(*GRPCMetric) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type metricsSendMetricClient struct {
	grpc.ClientStream
}

func (x *metricsSendMetricClient) Send(m *GRPCMetric) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metricsSendMetricClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *metricsClient) SendMetrics(ctx context.Context, in *GRPCMetric, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.Metrics/SendMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
// All implementations must embed UnimplementedMetricsServer
// for forward compatibility
type MetricsServer interface {
	// SendMetric отправка в потоке атомарной метрики
	SendMetric(Metrics_SendMetricServer) error
	// SendMetrics отправка слайса метрик
	SendMetrics(context.Context, *GRPCMetric) (*emptypb.Empty, error)
	mustEmbedUnimplementedMetricsServer()
}

// UnimplementedMetricsServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsServer struct {
}

func (UnimplementedMetricsServer) SendMetric(Metrics_SendMetricServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMetric not implemented")
}
func (UnimplementedMetricsServer) SendMetrics(context.Context, *GRPCMetric) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMetrics not implemented")
}
func (UnimplementedMetricsServer) mustEmbedUnimplementedMetricsServer() {}

// UnsafeMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServer will
// result in compilation errors.
type UnsafeMetricsServer interface {
	mustEmbedUnimplementedMetricsServer()
}

func RegisterMetricsServer(s grpc.ServiceRegistrar, srv MetricsServer) {
	s.RegisterService(&Metrics_ServiceDesc, srv)
}

func _Metrics_SendMetric_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricsServer).SendMetric(&metricsSendMetricServer{stream})
}

type Metrics_SendMetricServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*GRPCMetric, error)
	grpc.ServerStream
}

type metricsSendMetricServer struct {
	grpc.ServerStream
}

func (x *metricsSendMetricServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metricsSendMetricServer) Recv() (*GRPCMetric, error) {
	m := new(GRPCMetric)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Metrics_SendMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GRPCMetric)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).SendMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Metrics/SendMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).SendMetrics(ctx, req.(*GRPCMetric))
	}
	return interceptor(ctx, in, info, handler)
}

// Metrics_ServiceDesc is the grpc.ServiceDesc for Metrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMetrics",
			Handler:    _Metrics_SendMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMetric",
			Handler:       _Metrics_SendMetric_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "metrics.proto",
}
